---
title: "About this site"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# About the Hertie School Data Science Lab

The Hertie School Data Science Lab is a research and training hub that tackles societal challenges with computational and data-intensive methods. Our mission is to foster, advance and promote excellence in data science research, education and application to enable better decision-making for the common good.

Over the next decade, data science is expected to have a significant impact across all sectors of the economy and society through automation and personalization of services. The Hertie School Data Science Lab will leverage and amplify breakthroughs in data science and artificial intelligence (AI) to tackle major societal problems.

# About the Student Projects Showcase 

The primary aim of final projects from the lab's course offerings is to provide students with an opportunity to gain hands-on experience developing research projects in data science and applied machine learning. 

More information on the lab's course offerings can be found here: https://www.hertie-school.org/en/datasciencelab/teaching-services
